### ISSUE TITLE
It shows error on <style> tag in html file

### ISSUE THREAD

**Issue by littlee** [SublimeLinter/SublimeLinter-csslint#11]
When I insert a style tag in my html file, It always shows error on the tag
![qq 20150817161203](https://cloud.githubusercontent.com/assets/7534668/9300661/fe524f5c-44fa-11e5-9ef0-ac5024185288.png)

html code

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>

    <style type="text/css">

    </style>
</head>
<body>
</body>
</html>
```

**Comment by atilkan** [comment]
Yes, same for me too.

**Comment by MatiasFito** [comment]
Same here, i don't know what it wants it shows like 4 errors on each line

**Comment by ozmoroz** [comment]
Same here.

**Comment by Tathanen** [comment]
Ditto.

**Comment by Cheynas** [comment]
Found two self-closed issues ( #3 #6 ) with the same problem, from 2014.

I do not know enough about how to program for Sublime and SublimeLinter, but if nobody steps up and solves this permanently; when I have time over I might try to hack together a solution that works.
And then leave that ugly mess for a more qualified person to clean up and optimize.

**Comment by brainz80** [comment]
I too am having the same problem. Looked at the source code a bit. I believe the problem resides in SublimeLinter itself. Not this plugin. SublimeLinter seems to create a temporary CSS-file for all inline styles. I believe this file to be broken. Haven't yet been able to confirm this because the file gets removed right away.

**Comment by jehon** [comment]
Same problem here. How to fix that?

**Comment by rmarscher** [comment]
See https://github.com/SublimeLinter/SublimeLinter3/issues/356 and https://github.com/sublimehq/Packages/issues/106. It seems that there is no fix until those issues are resolved. The [SublimeLinter docs](http://www.sublimelinter.com/en/latest/usage.html#customized-syntax-definitions) mention they used to fix this with a custom HTML syntax file. But SublimeLinter seems to no longer do that as mentioned [here](https://github.com/SublimeLinter/SublimeLinter3/issues/356#issuecomment-157145289): "SublimeLinter used to supply syntaxes with this fixed, but were outdated to other syntax changes and were a bear to maintain so they were removed to use the default syntaxes." The issue that led to that removal can be seen here: https://github.com/SublimeLinter/SublimeLinter3/issues/278. Here's the last version of the HTML syntax that SublimeLinter used to provide: https://raw.githubusercontent.com/SublimeLinter/SublimeLinter3/ce29335059a0aecf7f8ef8c2b6b5e3b07a70542b/fixed-syntaxes/HTML/HTML.tmLanguage

It seems the SublimeText maintainers are looking for someone to supply a patch based on the feedback in https://github.com/sublimehq/Packages/issues/106.

YMMV, but I was able to fix the problem because I am on the Sublime Text 3 stable channel using version 3083. The forum discussion that led to SublimeLinter removing the custom HTML syntax was for versions after 3083. Here are the steps:

- Close any html files you have open in SublimeText.
- Use the 'Package Control: Disable Package' command to disable the HTML package. Or go to the `Preferences -> Settings - User` and add "HTML" to the "ignored_packages" setting array.
- Use the `Preferences -> Browse Packages...` menu option in ST3 to open your packages folder.
- Close SublimeText.
- Download SublimeLinter's previous custom [HTML.tmLanguage](https://raw.githubusercontent.com/SublimeLinter/SublimeLinter3/ce29335059a0aecf7f8ef8c2b6b5e3b07a70542b/fixed-syntaxes/HTML/HTML.tmLanguage) to the User folder inside the ST3 packages folder.
- Open SublimeText.

I'm not exactly sure if this problem still exists in the more recent versions of SublimeText 3. The latest HTML syntax source is here https://github.com/sublimehq/Packages/blob/master/HTML/HTML.sublime-syntax. If there's still a problem with extracting the css without the style tags, it's probably in the section that pushes to source.css.embedded.html. So fix that and submit a pull request. :)

**Comment by sekai92id** [comment]
Thanks @rmarscher it's works like magic

**Comment by rmarscher** [comment]
Build 3103 was released on the stable channel. If you update to that, it switches to use the `.sublime-syntax` files and unfortunately they still have the same problem. It seems the HTML.tmLanguage file is no longer recognized. I downloaded the [HTML.sublime-syntax](https://github.com/sublimehq/Packages/blob/master/HTML/HTML.sublime-syntax) file and put that in the `Packages/User` folder. I made some attempts to change the HTML syntax file using `meta_content_scope` instead of `meta_scope` for the push to `source.css.embedded.html`. That is slightly better. It doesn't include the closing style tag but it does include the `>` character of the opening style tag.

It seems that the `HTML.sublime-syntax` pushes the contents of the style tag to the `source.css` scope which is great. So I switched the selector in line 38 of `SublimeLinter-csslint/linter.py` to `'html': 'source.css'`. However, it now seems to include both the `source.css.embedded.html` and `source.css` scopes. It must be a prefix-based selector. I then changed the `source.css.embedded.html` scope in the `HTML.sublime-syntax` to another name so it didn't start with `source.css`. At this point, the linting for style tags was working correctly. However, `HTML.sublime-syntax` also pushes the contents of HTML style attributes to `source.css`. That would be great, because now style tag contents are linted... except the style tag contents aren't wrapped in braces with a selector, so that doesn't lint.

Those are the things I tried. It seems a real fix will require more extensive changes.

**Comment by groteworld** [comment]
As of sublimehq/Packages@0417e42 these changes have been made to the default HTML syntax. You will need newest build ST3103.

CSS may be having issue, I'm confirming in Packages issue sublimehq/Packages#106.

**Comment by groteworld** [comment]
https://github.com/sublimehq/Packages/commit/f9b9e10b8d38b233c1078a425b6c1c026a62aa63 fixes issues with `<style>` and `<script>` tags. Please upgrade to SublimeText 3103 and download the latest from master of https://github.com/sublimehq/Packages, or wait until the next ST release.

**Comment by niandubay** [comment]
Perfect! This error was driving me crazy! 

Thank you! :)

**Comment by aliavni** [comment]
thanks @rmarscher

**Comment by mohid108** [comment]
i'm experiencing that kind of error for both style and script tag my ST3 version is 3143 i've  saved HTML.tmLanguage as you say @rmarscher  and i've downloaded youtr git file @groteworld  but none can solve my problem please help other wise i've to change my editor this is actually irritating me .
![script error](https://user-images.githubusercontent.com/29270685/35767944-20d1d382-091f-11e8-8ddc-9be0e0e0dc1f.PNG)
